# migrations/versions/f2fa2eb8f195_add_data_corrections.py

"""add data_corrections

Revision ID: f2fa2eb8f195
Revises: 001_initial
Create Date: 2026-06-25
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2fa2eb8f195"
down_revision: str | None = "001_initial"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_corrections",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("document_id", sa.String(36), nullable=False),
        sa.Column("field_name", sa.String(100), nullable=False),
        sa.Column("original_value", sa.Text(), nullable=True),
        sa.Column("corrected_value", sa.Text(), nullable=True),
        sa.Column("adapter_used", sa.String(100), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name="data_corrections_document_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_corrections_document_id",
        "data_corrections",
        ["document_id"],
    )

    # Cambiar el tipo de status a Enum (opcional)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        "users_email_key",
        "users",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "documents",
        "status",
        existing_type=sa.Enum(
            "PENDING",
            "PROCESSING",
            "EXTRACTED",
            "FAILED",
            "NEEDS_REVIEW",
            name="documentstatus",
            native_enum=False,
            length=30,
        ),
        nullable=False,
    )
    op.drop_constraint(
        "data_corrections_document_id_fkey",
        "data_corrections",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "data_corrections_document_id_fkey",
        "data_corrections",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "data_corrections_document_id_fkey",
        "data_corrections",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "data_corrections_document_id_fkey",
        "data_corrections",
        "documents",
        ["document_id"],
        ["id"],
    )
    op.alter_column(
        "documents",
        "status",
        existing_type=sa.Enum(
            "PENDING",
            "PROCESSING",
            "EXTRACTED",
            "FAILED",
            "NEEDS_REVIEW",
            name="documentstatus",
            native_enum=False,
            length=30,
        ),
        type_=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.drop_index("idx_corrections_document_id", table_name="data_corrections")
    op.drop_table("data_corrections")
    # ### end Alembic commands ###