name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/checkout@v4
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: |
        python -m pip upgrade pip
        pip install -r requirements.txt  # O tu archivo de dependencias
        pip install pytest pytest-cov

    - name: Ejecutar Tests con Cobertura
      run: |
        pytest --cov=app --cov-report=xml

    # Este paso conecta con el badge de Codecov que tienes en tu README
    - name: Subir reporte a Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false
        # Si tu repo es público, a veces no necesitas token. Si es privado, usa:
        # token: ${{ secrets.CODECOV_TOKEN }}